### ISSUE TITLE
Make it easy to deploy a substrate-connect enabled bootnode to Kubernetes

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#108]
Substrate-connect light clients have been officially announced as ready to use for the general public (https://www.youtube.com/watch?v=TDbTCrDDO2U). However, from an operational point of view, an obstacle to adoption is that to work properly, the light client needs to access a bootnode which exposes it's p2p over websocket (typically `--listen-addr /ip4/0.0.0.0/tcp/30444/ws --listen-addr /ip6/::/tcp/30444/ws`). Moreover, as browsers will only allow connecting to a secured websocket, you need a reverse proxy in front such as nginx to add a letsencrypt certificate.

I believe it would be valuable to offer an easy way to deploy such a bootnode to kubernetes with the following:
- ~Option to auto-generate the relevant p2p-ws Ingress and Service on the helm-chart~
- Example config showing how to set up an ingress controller and [external-dns](https://github.com/kubernetes-sigs/external-dns) / [cert-manager](https://cert-manager.io/docs/) for automatic certificate management.

ping @tomaka

**Comment by tomaka** [comment]
To give more context, we're planning on integrating support for WebRTC in Substrate. WebRTC is basically an equivalent to WebSocket, but more suited to our use case.
Eventually you would use `--listen-addr .../webrtc/...` instead, and you wouldn't need any TLS certificate.
Also, because WebRTC uses UDP, we can make it use the same port as TCP, which makes configuration more simple.

However, the timeline for WebRTC is probably a few months, so it's probably still worth doing a helm chart.

**Comment by PierreBesson** [comment]
Service part handled in https://github.com/paritytech/helm-charts/pull/165
As for the p2p-ws Ingress, I'm not sure if it should be part of the node chart or a different chart.

**Comment by bakhtin** [comment]
I would not include the Ingress part in the chart. The chart is using only standard Kubernetes primitives that enables it to work on different Kubernetes distributions: be it self-hosted or a managed cloud solution. I would leave the chart as generic as possible and allow users to customize it to their needs.

**Comment by PierreBesson** [comment]
Also the bootnodes being the first node you set up for your network, it might be good to show some examples directly in the node chart readme. Alternatively this can be discussed in the [devops guide](https://paritytech.github.io/devops-guide)

**Comment by bakhtin** [comment]
I created a separate issue to put some examples of using Ingress: https://github.com/paritytech/helm-charts/issues/175

**Comment by lazam** [comment]
We can create a chart called `polkadot-stack` which is similar on how `kube-prometheus-stack` is designed. The `polkadot-stack` chart will use different charts as it's dependency to easily deploy a full blown solution with auxiliary services such as ingress, polkadot-introspector, substrate-connect, and others. This approach will help us to allow each individual stack to be cloud agnostic but still have a chart to allow the community to deploy a solution with the necessary configs and design.

**Comment by PierreBesson** [comment]
@lazam this sounds like an excellent idea, maybe it could be done as part as https://github.com/paritytech/helm-charts/issues/97, where we could have `polkadot-stack` and `polkadot-parachain-stack`.

**Comment by dblane-digicatapult** [comment]
Would you envisage this being an umbrella chart (and thus using subcharts) or using something like [helmfile](https://github.com/helmfile/helmfile/) to create those stacks?
