### ISSUE TITLE
HPA scaling event does not handle creation of p2p services

### ISSUE THREAD

**Issue by bakhtin** [paritytech/helm-charts#124]
Horizontal Pod Autoscaler added in https://github.com/paritytech/helm-charts/pull/120 when enabled conditionally removes `replicas` field from the StatefulSet. Creation of [p2p services](https://github.com/paritytech/helm-charts/blob/main/charts/node/templates/service.yaml#L37-L38) relies on the presence of that field. Thus when replica count is scaled up or down by HPA additional p2p services are not created/removed and no Pods can work.

We need to check whether Helm has any mechanism to rely on the current replicas set by HPA. Or, if not implement some custom handler that monitors K8s scaling events and creates/removes p2p services accordingly

**Comment by dblane-digicatapult** [comment]
An easier solution might be to change the logic in service creation.

E.G.
```
{{range $i := until (max .Values.autoscaling.maxReplicas .Values.node.replicas | int) }}
{{- if $.Values.node.perNodeServices.apiService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}
```

**Comment by dblane-digicatapult** [comment]
@bakhtin I'm happy to pick this one up if you'd like.

**Comment by bakhtin** [comment]
Sure. Feel free to pick this one up. The proposed workaround would work for the time being.
