### ISSUE TITLE
Add CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#135]
We want to encourage people outside of Parity to contribute to this repository.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by PierreBesson** [comment]
I found those guidelines to be good https://github.com/timescale/helm-charts/blob/main/CONTRIBUTING.md

**Comment by bakhtin** [comment]
Done in https://github.com/paritytech/helm-charts/pull/298
