### ISSUE TITLE
Manage node key operations using subkey

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#168]
As pointed out in [this discussion](https://github.com/paritytech/helm-charts/pull/161#discussion_r986930668), the `node key` commands might not always be available on node binaries, we should switch to using the [`parity/subkey:latest` docker image](https://hub.docker.com/r/parity/subkey/tags).

**Comment by BulatSaif** [comment]
we also have `inject-keys` initcontainer with `{{ $.Values.node.command }} key insert` command, it also will fail if `node key` command  is not available.

**Comment by PierreBesson** [comment]
Since `inject-keys` uses the `node key insert` subcommand not available in `subkey`, it's not possible to replace all instances of `node key` by `subkey. So as we strictly depend on the `node key` subcommand being available it's not a great idea to add an additional dependency on the subkey docker image.
