### ISSUE TITLE
Revamp node helm-chart YAML templates

### ISSUE THREAD

**Issue by aardbol** [paritytech/helm-charts#204]
[node Helm chart templates](https://github.com/paritytech/helm-charts/tree/main/charts/node/templates) are missing some of the configurable parameters available in Kubernetes (like loading environment variables from a ConfigMap using `envFrom`). 
It is time-consuming (though rewarding on larger scale) to maintain our own standardized library of Helm templates. So instead I re-used the great [template library](https://github.com/bitnami/charts/tree/master/template/CHART_NAME/templates) from Bitnami during the development of [staking-miner](https://github.com/paritytech/helm-charts/tree/main/charts/staking-miner) Helm chart

A node Helm chart templates should be refactored in the same way to be consistent with available Kubernetes features

**Comment by PierreBesson** [comment]
Closing this as we scraped our initial plan to migrate to Bitnami templates for the node helm-chart.
