### ISSUE TITLE
Add jaeger-agent/grafana-agent sidecar option

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#26]
Add an option to the node helm chart for doing the following:

- Run [jaeger-agent](https://www.jaegertracing.io/docs/1.28/deployment/#agent) or [grafana agent](https://grafana.com/docs/tempo/latest/grafana-agent/) as a sidecar of the node pod to receive traces
- Configure the agent to forward traces to the Jaeger/Tempo collector URL
- Add the `--jaeger-agent 127.0.0.1:$AGENT_PORT` flag to the node

**Comment by lazam** [comment]
Resolving this one since #27 is merged already.
