### ISSUE TITLE
[node] Check if node id defined multiple times 

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/helm-charts#349]
If we have `persistGeneratedNodeKey: true`, the injected key from the vault is ignored. It's likely a mistake that a dynamically generated random key is preferred over an intentionally set ID.

Task:
- [x] Add a check in the Helm chart to ensure that the node ID is defined only once.

**Comment by PierreBesson** [comment]
:+1: we should fail fast if the node key is defined more than 1 times as it is most likely a misconfiguration.

**Comment by BulatSaif** [comment]
Fixed in: https://github.com/paritytech/helm-charts/pull/353
