### ISSUE TITLE
Use static version instead of `tag: latest` for the node helm chart

### ISSUE THREAD

**Issue by ArshamTeymouri** [paritytech/helm-charts#41]
Currently, when a new polkadot release is available, people should change their values files to point to the new version.
I think the best is to release a new version for the `node` helm chart per each release and use the chart `appVersion` as default for the image tag, then people who are using our chart for their deployment can easily update their nodes by bumping the chart version instead of editing the `values.yaml` file manually or by a pipeline.

**Comment by PierreBesson** [comment]
It doesn't make sense to me to do it and will be a big maintainance burger. Moreover, the node chart doesn't support only polkadot but also any other substrate chain, so it would not make sense to release new version of the chart containing just a change of the default tag for `parity/polkadot`. However, using `latest` allows us to be up to date for dependency scanners. Users should know that the version has to be overridden with a static one or risk unpredictable behavior but that's just basic knowledge.

**Comment by ArshamTeymouri** [comment]
well, this is the usual thing that all the great companies do for their helm charts. Supporting polkadot and other substrate chains don't interfere with having the version pinned in the helm chart instead of using the latest tag imo. I believe that's also the idea behind having APP VERSION in all the `Chart.yaml` files -- to specify which version of the app will be installed by the helm chart.
we might have bigger fishes to fry for now, but I would call this something nice to have in the future. Still, if it doesn't make sense, feel free to close the issue.

**Comment by dblane-digicatapult** [comment]
Just to chime in, if you look at organisations that maintain a large amount of helm charts I.E. Bitnami they always pin to an `image.tag` in their `values.yaml`

With a helm chart you ideally are looking for stability as a default behaviour and using tag `latest` removes that.

**Comment by PierreBesson** [comment]
For me, it would be okay to set the version explicitly if we can have an automated bot submitting PRs when new version are available.
Apparently helm-charts are not supported by dependabot, but there is [renovate-bot](https://docs.renovatebot.com/).

**Comment by dblane-digicatapult** [comment]
Another alternative is submitting the charts to ArtifactHub and annotating the charts as per https://artifacthub.io/docs/topics/annotations/helm/

Although it's not perfect for a github native approach.

**Comment by PierreBesson** [comment]
My conclusion about this topic is that it's not useful to set something different than `image.tag=latest` for the node helm-chart default. If we create a umbrella polkadot and polkadot-parachain umbrella chart, then the latest released tag can be se't there (see https://github.com/paritytech/helm-charts/issues/97).
