### ISSUE TITLE
Rename helper templates in node chart

### ISSUE THREAD

**Issue by dblane-digicatapult** [paritytech/helm-charts#47]
Since helm [v3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0) we have the option to refer to a [subcharts templated helper functions](https://github.com/helm/helm/commit/3daaea0a1cc625c2dfe2db4149bc45d39a660cf2).  However if the parent chart uses identically named helper templates then the child ones will be overwritten.

Additionally `chart.name` is fairly close to `Chart.name` which is a helm builtin object as we should move to avoid confusion.
I suggest we change the naming of these functions from `chart.blah` to `node.blah` or some other nomenclature to avoid helper templates being overwritten when called from a parent chart.

**Comment by PierreBesson** [comment]
To me this sounds reasonable and useful. Does anyone have an opinion of the potential impacts and disadvantages that this change could have ?
