### ISSUE TITLE
Using HashiCorp Vault in Helm Charts

### ISSUE THREAD

**Issue by kaverikhaneja** [paritytech/helm-charts#50]
Would like to use HashiCorp Vault in Susbtrate/Polkadot helm charts for secret management and protecting sensitive data, in this case, the node keys, for instance.

**Comment by PierreBesson** [comment]
We have achieved such an integration with other Kubernetes deployments, using the [Vault agent injector](https://www.vaultproject.io/docs/platform/k8s/injector) and the [proper annotations](https://www.vaultproject.io/docs/platform/k8s/injector/annotations). However configuring the Vault itself can be quite complex and is outside the scope of the helm-chart. We should just let users map the KV paths and policy they want to use for each key, leaving authentication concerns to the cluster administrator.
