### ISSUE TITLE
[node] Add second Prometheus port  to `serviceMonitor` for collator node 

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/helm-charts#77]
## Description 
If `collator.isParachain` set to `true`, node exposes 2 Prometheus ports (relaychain and  parachain),  If monitoring is enabled both ports should be scraped. 

## Current behavior 
Only parachain metrics are collected. 

## Expected behavior 
Both parachain and relaychain  metrics collected.

**Comment by lazam** [comment]
https://github.com/paritytech/helm-charts/pull/87
