### ISSUE TITLE
Create an umbrella charts for "polkadot-stack" and polkadot-parachain-stack"

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#97]
We should create dedicated charts to provide standardized deployment of [polkadot](https://github.com/paritytech/polkadot) and polkadot-parachain ([cumulus](https://github.com/paritytech/cumulus)). Those would be wrappers around the generic "node" helm-chart with values correctly set for their respective latest image tag as well as more comprehensive docs on how to correctly configure them.

- For simplicity, the chart version could be equal to the polkadot/cumulus release version.
- We need to find a way to semi-automate version upgrades.
- This is the opportunity to add end 2 end chart tests to validate that the node can connect to the network.

Update:
As agreed upon this [comment](https://github.com/paritytech/helm-charts/issues/108#issuecomment-1273983683), this chart will now be a `polkadot-stack` chart and `polkadot-parachain-stack`.

docker images in use to be wrapped with the umbrella chart:

- https://hub.docker.com/r/parity/polkadot (release)
- https://hub.docker.com/r/paritypr/polkadot-debug (debug)

- https://hub.docker.com/r/parity/polkadot-parachain
- https://hub.docker.com/r/paritypr/polkadot-parachain-debug

**Comment by BulatSaif** [comment]
This should be done after/together with  https://github.com/paritytech/helm-charts/issues/142 to avoid double work.

**Comment by PierreBesson** [comment]
@lazam do you have plans to work on this ?

**Comment by lazam** [comment]
> @lazam do you have plans to work on this ?

I'm planning to work on this though we need to have some discussion about this to have better clarity on the roadmap, but if you want to pick this one then I'm good with it.

**Comment by lovelaced** [comment]
What are the current thoughts on this?

**Comment by PierreBesson** [comment]
Closing in favor of #314 and #315
